package com.actify.financialledger.audit.entity;

public enum AuditAction {
	USER_REGISTERED,
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	ACCOUNT_CREATED,
	DEPOSIT,
	WITHDRAWAL,
	TRANSFER,
	REVERSAL,
	INTEREST_CREDIT,
	FRAUD_REJECTED,
	TRANSACTION_REJECTED,
	ACCESS_DENIED
}
